import { Upload } from './upload';

export interface MessageRequest {

    textContent?: string;
    sentVolume?: number;
    creditCost?: number;
    imageUrl?: string;
    numberRangeUrl?: string;
    dataReportUrl?: string;
    createdAt?: string;
    sentAt?: string;
    completedAt?: string;
    disapprove?: string;
    approve?: string;
    userName?: string;
    userId?: string;
    requestStatus?: RequestStatus;

}

export enum RequestStatus {
    PENDING_REVIEW = "等待审核",    //Submitted requests pending for review
    APPROVED = "正在发送",         //Requests passed review, ready to send out
    REJECTED = "敏感内容 系统审核未通过",       //Requests failed to pass review, was dropped and need to be resubmit
    COMPLETED = "发送完成"        //Requests are completed for all send out task, data report should be generated by this point
}

